// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateOrderRequest struct {
	Price     int       `json:"price"`
	ProductID ProductId `json:"productId"`
}

type CreateOrderResponse struct {
	OrderID OrderId `json:"orderId"`
}

type GetOrdersRequest struct {
	OrderIds   []OrderId   `json:"orderIds,omitempty"`
	UserIds    []UserId    `json:"userIds,omitempty"`
	ProductIds []ProductId `json:"productIds,omitempty"`
	Prices     []int       `json:"prices,omitempty"`
}

type GetOrdersResponse struct {
	Orders []Order `json:"orders"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
