// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateProductRequest struct {
	Item       string                 `json:"item"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

type CreateProductResponse struct {
	ProductID ProductId `json:"product_id"`
}

type GetProductsRequest struct {
	ProductIds []ProductId            `json:"productIds,omitempty"`
	Items      []string               `json:"items,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

type GetProductsResponse struct {
	Products []FullProduct `json:"products"`
}
